plugins { id 'com.android.application' }

android {
    namespace 'com.jili.v1'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jili.v1'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
